let%expect_test "punctuators" =
  Test.test_lexer
    {|
[](){}.->
++--&*+-~!
/%<<>><><=>===!=^|&&||
?:;...
=*=/=%=+=-=<<=>>=&=^=|=
,###
<::><%%>%:%:%:
|};
  [%expect
    {|
    1:1   NewLine                 lexeme="\n"
    2:1   LeftBracket             lexeme="["
    2:2   RightBracket            lexeme="]"
    2:3   LeftParen               lexeme="("
    2:4   RightParen              lexeme=")"
    2:5   LeftBrace               lexeme="{"
    2:6   RightBrace              lexeme="}"
    2:7   Period                  lexeme="."
    2:8   Arrow                   lexeme="->"
    2:10  NewLine                 lexeme="\n"
    3:1   PlusPlus                lexeme="++"
    3:3   MinusMinus              lexeme="--"
    3:5   And                     lexeme="&"
    3:6   Star                    lexeme="*"
    3:7   Plus                    lexeme="+"
    3:8   Minus                   lexeme="-"
    3:9   Tilde                   lexeme="~"
    3:10  Bang                    lexeme="!"
    3:11  NewLine                 lexeme="\n"
    4:1   Slash                   lexeme="/"
    4:2   Percent                 lexeme="%"
    4:3   LessLess                lexeme="<<"
    4:5   GreaterGreater          lexeme=">>"
    4:7   Less                    lexeme="<"
    4:8   Greater                 lexeme=">"
    4:9   LessEqual               lexeme="<="
    4:11  GreaterEqual            lexeme=">="
    4:13  EqualEqual              lexeme="=="
    4:15  BangEqual               lexeme="!="
    4:17  Caret                   lexeme="^"
    4:18  Or                      lexeme="|"
    4:19  AndAnd                  lexeme="&&"
    4:21  OrOr                    lexeme="||"
    4:23  NewLine                 lexeme="\n"
    5:1   Question                lexeme="?"
    5:2   Colon                   lexeme=":"
    5:3   Semicolon               lexeme=";"
    5:4   Ellipses                lexeme="..."
    5:7   NewLine                 lexeme="\n"
    6:1   Equal                   lexeme="="
    6:2   StarEqual               lexeme="*="
    6:4   SlashEqual              lexeme="/="
    6:6   PercentEqual            lexeme="%="
    6:8   PlusEqual               lexeme="+="
    6:10  MinusEqual              lexeme="-="
    6:12  LessLessEqual           lexeme="<<="
    6:15  GreaterGreaterEqual     lexeme=">>="
    6:18  AndEqual                lexeme="&="
    6:20  CaretEqual              lexeme="^="
    6:22  OrEqual                 lexeme="|="
    6:24  NewLine                 lexeme="\n"
    7:1   Comma                   lexeme=","
    7:2   HashHash                lexeme="##"
    7:4   Hash                    lexeme="#"
    7:5   NewLine                 lexeme="\n"
    8:1   LeftBracket             lexeme="<:"
    8:3   RightBracket            lexeme=":>"
    8:5   LeftBrace               lexeme="<%"
    8:7   RightBrace              lexeme="%>"
    8:9   HashHash                lexeme="%:%:"
    8:13  Hash                    lexeme="%:"
    8:15  NewLine                 lexeme="\n"
    8:15  Eof                     lexeme="\n"
    |}]
