let%expect_test "too many includes" =
  Test.test_pp
    ~initial_src:{ name = "one.c"; contents = "#include <two.c>" }
    [ { name = "two.c"; contents = "#include <one.c>" } ];
  [%expect
    {|
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    In file included from one.c:1:1
    In file included from two.c:1:1
    [1mone.c:1:10[0m: [1;31mfatal error[0m: [1mmaximum include depth exceeded[0m
        1 | #include <two.c>
          |          [1;32m^[0m
    Exit called with code 1
    |}]
